# Generated by Django 5.2.4 on 2026-08-11 05:29

import common.utils.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100, 'درصد تخفیف باید بین 0 و 100 باشد.')], verbose_name='درصد تخفیف')),
                ('type', models.CharField(choices=[('R', 'بازنشسته'), ('F', 'هیأت علمی'), ('E', 'کارمند'), ('C', 'کارمند شرکتی')], max_length=1, unique=True, verbose_name='نوع تخفیف')),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیف ها',
            },
        ),
        migrations.CreateModel(
            name='InsurancePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('start_date', models.DateField(verbose_name='تاریخ آغاز دوره')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان دوره')),
                ('main_cost', models.PositiveBigIntegerField(verbose_name='هزینه اصلی (سرپرست خانوار)')),
                ('family_member_cost', models.PositiveBigIntegerField(verbose_name='هزینه افراد تحت تکفل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
            ],
            options={
                'verbose_name': 'دوره بیمه تکمیلی',
                'verbose_name_plural': 'دوره های بیمه تکمیلی',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='نام')),
                ('last_name', models.CharField(max_length=255, verbose_name='نام خانوادگی')),
                ('national_code', common.utils.fields.NationalCodeField(db_index=True, max_length=10, verbose_name='کد ملی')),
                ('father_name', models.CharField(blank=True, max_length=255, verbose_name='نام پدر')),
                ('birth_date', models.DateField(verbose_name='تاریخ تولد')),
                ('gender', models.CharField(choices=[('M', 'آقا'), ('F', 'خانم')], max_length=1, verbose_name='جنسیت')),
                ('birth_certificate_number', models.CharField(blank=True, max_length=20, verbose_name='شماره شناسنامه')),
                ('family_role', models.CharField(choices=[('H', 'همسر'), ('C', 'فرزند'), ('F', 'پدر'), ('M', 'مادر'), ('S', 'خواهر'), ('B', 'برادر')], max_length=1, verbose_name='نقش در خانواده')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره موبایل')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
                ('insured', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to=settings.AUTH_USER_MODEL, verbose_name='بیمه\u200cشده اصلی')),
                ('insurance_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insured_family_members', to='main.insuranceperiod', verbose_name='دوره بیمه تکمیلی')),
            ],
            options={
                'verbose_name': 'عضو خانواده',
                'verbose_name_plural': 'اعضای خانواده',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
