# Generated by Django 5.2.4 on 2026-08-17 07:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_year', models.PositiveSmallIntegerField(verbose_name='سال قرارداد')),
                ('insurer_company', models.CharField(max_length=200, verbose_name='شرکت بیمه طرف قرارداد')),
                ('terms_file', models.FileField(upload_to='contracts/', verbose_name='فایل قرارداد بیمه')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع پوشش')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان پوشش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'قرارداد بیمه',
                'verbose_name_plural': 'قراردادهای بیمه',
                'ordering': ['-contract_year'],
                'constraints': [models.UniqueConstraint(fields=('contract_year',), name='unique_insurance_contract_year'), models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='contract_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='CostRateRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(choices=[('R', 'بازنشسته'), ('F', 'هیات علمی'), ('E', 'کارمند'), ('C', 'کارمند شرکتی')], max_length=1, verbose_name='نوع استخدام')),
                ('cost_type', models.CharField(choices=[('H', 'استخدام شده'), ('F', 'پدر'), ('M', 'مادر'), ('C', 'فرزند'), ('S', 'همسر')], max_length=1, verbose_name='نوع رابطه برای محاسبه قیمت')),
                ('subsidy_percent', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, 'حداقل درصد یارانه، صفر درصد است.'), django.core.validators.MaxValueValidator(100, 'حداکثر درصد یارانه، 100 درصد است.')], verbose_name='درصد تخفیف یارانه')),
                ('base_premium_cost', models.PositiveBigIntegerField(default=0, verbose_name='هزینه پایه بابت بیمه')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_rules', to='main.insurancecontract', verbose_name='قرارداد بیمه سالانه')),
            ],
            options={
                'verbose_name': 'قانون هزینه و یارانه بیمه',
                'verbose_name_plural': 'قوانین هزینه و یارانه بیمه',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('national_code', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('birth_certificate_number', models.CharField(blank=True, max_length=20, verbose_name='شماره شناسنامه')),
                ('father_name', models.CharField(blank=True, max_length=100, verbose_name='نام پدر')),
                ('mother_name', models.CharField(blank=True, max_length=100, verbose_name='نام مادر')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('birth_place', models.CharField(blank=True, max_length=150, verbose_name='محل تولد')),
                ('gender', models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], max_length=1, verbose_name='جنسیت')),
                ('is_household_head', models.BooleanField(default=False, verbose_name='سرپرست خانوار است؟')),
                ('national_id_serial', models.CharField(blank=True, max_length=20, verbose_name='سریال کارت ملی')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='شماره موبایل')),
                ('landline_number', models.CharField(blank=True, max_length=20, verbose_name='شماره تلفن ثابت')),
                ('address', models.TextField(blank=True, verbose_name='نشانی')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='کد پستی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='household_members', to='main.person', verbose_name='سرپرست')),
            ],
            options={
                'verbose_name': 'فرد',
                'verbose_name_plural': 'افراد',
            },
        ),
        migrations.CreateModel(
            name='FamilyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('F', 'پدر'), ('M', 'مادر'), ('C', 'فرزند'), ('S', 'همسر')], max_length=1, verbose_name='نوع رابطه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='main.person', verbose_name='فرد')),
                ('related_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='main.person', verbose_name='فرد مرتبط')),
            ],
            options={
                'verbose_name': 'رابطه خانوادگی',
                'verbose_name_plural': 'روابط خانوادگی',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('D', 'پیش نویس'), ('S', 'ارسال شده'), ('C', 'تایید شده')], max_length=1, verbose_name='وضعیت')),
                ('terms_accepted', models.BooleanField(default=False, verbose_name='تایید مطالعه قرارداد')),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید قرارداد')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='main.insurancecontract', verbose_name='قرارداد بیمه سالانه')),
                ('covered_members', models.ManyToManyField(related_name='enrollments', to='main.person', verbose_name='افراد تحت پوشش')),
            ],
            options={
                'verbose_name': 'ثبت نام سالانه سرپرست',
                'verbose_name_plural': 'ثبت نام های سالانه سرپرست ها',
            },
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['last_name', 'first_name'], name='main_person_last_na_958d12_idx'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('household__isnull', True), ('is_household_head', True)), models.Q(('household__isnull', False), ('is_household_head', False)), _connector='OR'), name='valid_household_assignment'),
        ),
        migrations.AddIndex(
            model_name='familyrelationship',
            index=models.Index(fields=['person', 'relationship_type'], name='main_family_person__57cfc9_idx'),
        ),
        migrations.AddIndex(
            model_name='familyrelationship',
            index=models.Index(fields=['related_person', 'relationship_type'], name='main_family_related_bb19df_idx'),
        ),
        migrations.AddConstraint(
            model_name='familyrelationship',
            constraint=models.UniqueConstraint(fields=('person', 'related_person', 'relationship_type'), name='unique_family_relationship'),
        ),
        migrations.AddConstraint(
            model_name='familyrelationship',
            constraint=models.CheckConstraint(condition=models.Q(('person', models.F('related_person')), _negated=True), name='person_cannot_be_related_to_itself'),
        ),
    ]
