# Generated by Django 5.2.4 on 2026-08-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_currentinsurancecontract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('D', 'پیش نویس'), ('P', 'در انتظار پرداخت'), ('S', 'ارسال شده'), ('C', 'تایید شده')], default='D', max_length=1, verbose_name='وضعیت'),
        ),
    ]
