# Generated by Django 5.2.4 on 2026-08-22 04:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_enrollment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="costraterule",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("R", "بازنشسته"),
                    ("F", "هیات علمی"),
                    ("E", "کارمند"),
                    ("C", "کارمند شرکتی"),
                ],
                max_length=1,
                verbose_name="نوع استخدام",
            ),
        ),
        migrations.CreateModel(
            name="EmploymentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ساخت"),
                ),
            ],
            options={
                "verbose_name": "نوع استخدام",
                "verbose_name_plural": "انواع استخدام",
            },
        ),
        migrations.RemoveConstraint(
            model_name="familyrelationship",
            name="unique_family_relationship",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="terms_accepted",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="terms_accepted_at",
        ),
        migrations.AddField(
            model_name="enrollment",
            name="enrolled_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="زمان ثبت نام",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "در انتظار پرداخت"),
                    ("S", "ارسال شده"),
                    ("C", "تایید شده"),
                ],
                default="P",
                max_length=1,
                verbose_name="وضعیت",
            ),
        ),
        migrations.AddConstraint(
            model_name="familyrelationship",
            constraint=models.UniqueConstraint(
                fields=("person", "related_person"), name="unique_family_relationship"
            ),
        ),
        migrations.AddField(
            model_name="costraterule",
            name="employment_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.employmenttype",
                verbose_name="نوع استخدام",
            ),
        ),
    ]
