# Generated by Django 5.2.4 on 2026-08-30 07:20

import core.storage
import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_employmenttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenttype',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ساخت'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrolled_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ثبت نام'),
        ),
        migrations.AlterField(
            model_name='familyrelationship',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='insurancecontract',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='insurancecontract',
            name='end_date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ پایان پوشش'),
        ),
        migrations.AlterField(
            model_name='insurancecontract',
            name='start_date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ شروع پوشش'),
        ),
        migrations.AlterField(
            model_name='insurancecontract',
            name='terms_file',
            field=models.FileField(storage=core.storage.MediaStorage, upload_to='contracts/', verbose_name='فایل قرارداد بیمه'),
        ),
        migrations.AlterField(
            model_name='insurancecontract',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین ویرایش'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='InsuranceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='main.insurancecontract', verbose_name='قرارداد بیمه')),
            ],
            options={
                'verbose_name': 'پیشنهاد بیمه (سطح بندی)',
                'verbose_name_plural': 'پیشنهادات بیمه (سطح بندی ها)',
            },
        ),
    ]
