# Generated by Django 5.2.4 on 2026-09-01 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_employmenttype_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='contract',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='offer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='main.insuranceoffer', verbose_name='پیشنهاد بیمه سالانه'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CostRateRule',
        ),
    ]
