# Generated by Django 5.2.4 on 2026-09-01 07:15

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_enrollment_contract_enrollment_offer_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='insurancecontract',
            name='contract_end_after_start',
        ),
        migrations.RenameField(
            model_name='insurancecontract',
            old_name='end_date',
            new_name='coverage_end_date',
        ),
        migrations.RenameField(
            model_name='insurancecontract',
            old_name='start_date',
            new_name='coverage_start_date',
        ),
        migrations.AddField(
            model_name='insurancecontract',
            name='poll_end_date',
            field=django_jalali.db.models.jDateField(default=django.utils.timezone.now, verbose_name='تاریخ پایان نظرسنجی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insurancecontract',
            name='poll_start_date',
            field=django_jalali.db.models.jDateField(default=django.utils.timezone.now, verbose_name='تاریخ شروع نظرسنجی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insurancecontract',
            name='signup_end_date',
            field=django_jalali.db.models.jDateField(default=django.utils.timezone.now, verbose_name='تاریخ پایان ثبت نام'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insurancecontract',
            name='signup_start_date',
            field=django_jalali.db.models.jDateField(default=django.utils.timezone.now, verbose_name='تاریخ شروع ثبت نام'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='insurancecontract',
            constraint=models.CheckConstraint(condition=models.Q(('coverage_end_date__gte', models.F('coverage_start_date'))), name='contract_end_after_start'),
        ),
    ]
