# Generated by Django 5.2.4 on 2026-09-01 13:28

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_end_date_insurancecontract_coverage_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='account_number',
            field=models.CharField(default='', max_length=20, verbose_name='شماره حساب'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='available_services',
            field=models.CharField(default='', max_length=1024, verbose_name='خدمات قابل ارائه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='bc_issuance_place',
            field=models.CharField(default='', max_length=255, verbose_name='محل صدور شناسنامه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='bc_issuance_province',
            field=models.CharField(default='', max_length=255, verbose_name='استان محل صدور شناسنامه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='birth_day',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='روز تولد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='birth_month',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ماه تولد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='birth_year',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='سال تولد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='card_number',
            field=models.CharField(default='', max_length=16, verbose_name='شماره کارت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='changes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد تغییرات'),
        ),
        migrations.AddField(
            model_name='person',
            name='deployed_unit',
            field=models.CharField(default='', max_length=255, verbose_name='واحد مستقر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='person',
            name='education_certificate',
            field=models.CharField(default='', max_length=255, verbose_name='مدرک تحصیلی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='extra_text_5',
            field=models.TextField(blank=True, verbose_name='متن اضافه 5'),
        ),
        migrations.AddField(
            model_name='person',
            name='extra_text_6',
            field=models.TextField(blank=True, verbose_name='متن اضافه 6'),
        ),
        migrations.AddField(
            model_name='person',
            name='extra_text_7',
            field=models.TextField(blank=True, verbose_name='متن اضافه 7'),
        ),
        migrations.AddField(
            model_name='person',
            name='extra_text_8',
            field=models.TextField(blank=True, verbose_name='متن اضافه 8'),
        ),
        migrations.AddField(
            model_name='person',
            name='extra_text_9',
            field=models.TextField(blank=True, verbose_name='متن اضافه 9'),
        ),
        migrations.AddField(
            model_name='person',
            name='iba_number',
            field=models.CharField(default='', max_length=30, verbose_name='شماره شبا'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='insured_computer_code',
            field=models.CharField(default='', max_length=54, verbose_name='کد رایانه بیمه شده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='organizational_unit',
            field=models.CharField(default='', max_length=255, verbose_name='واحد سازمانی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='post_title',
            field=models.CharField(default='', max_length=255, verbose_name='عنوان پست'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='tracking_code',
            field=models.CharField(default='', max_length=45, verbose_name='کد رهگیری'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='veteran_status',
            field=models.CharField(choices=[('V', 'ایثارگر'), ('D', 'جانباز'), ('S', 'همسر شهید'), ('C', 'فرزند شهید'), ('F', 'آزاده'), ('N', 'ندارد')], default='', max_length=1, verbose_name='وضعیت ایثارگری'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ثبت'),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='زمان آخرین تغییرات'),
        ),
    ]
