# Generated by Django 5.2.4 on 2026-09-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_person_account_number_person_available_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='total_cost',
            field=models.PositiveBigIntegerField(default=0, verbose_name='هزینه نهایی'),
            preserve_default=False,
        ),
    ]
