# Generated by Django 5.2.4 on 2026-09-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_person_account_number_remove_person_address_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='person',
            name='valid_household_assignment',
        ),
        migrations.AlterField(
            model_name='person',
            name='relation_type',
            field=models.CharField(blank=True, choices=[('F', 'پدر'), ('M', 'مادر'), ('C', 'فرزند پسر'), ('D', 'فرزند دختر'), ('S', 'همسر')], max_length=1, null=True, verbose_name='نسبت با سرپرست'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('household__isnull', True), ('is_household_head', True), ('relation_type__isnull', True)), models.Q(('household__isnull', False), ('is_household_head', False), ('relation_type__isnull', False)), _connector='OR'), name='valid_household_assignment'),
        ),
    ]
