# Generated by Django 5.2.4 on 2026-09-12 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_person_valid_household_assignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAnschoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024, verbose_name='متن گزینه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
            ],
            options={
                'verbose_name': 'گزینه نظرسنجی',
                'verbose_name_plural': 'گزینه های نظرسنجی',
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024, verbose_name='متن سوال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
            ],
            options={
                'verbose_name': 'سوال نظرسنجی',
                'verbose_name_plural': 'سوالات نظرسنجی',
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('anschoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.surveyanschoice', verbose_name='گزینه')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.enrollment', verbose_name='ثبت نام بیمه')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.surveyquestion', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'پاسخ نظرسنجی',
                'verbose_name_plural': 'پاسخ های نظرسنجی',
            },
        ),
    ]
