# Generated by Django 5.2.4 on 2026-09-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_surveyanschoice_surveyquestion_surveyanswer'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='surveyanswer',
            constraint=models.UniqueConstraint(fields=('anschoice', 'enrollment', 'question'), name='survey_answer_unq'),
        ),
    ]
