# Generated by Django 5.2.4 on 2026-09-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_surveyanswer_survey_answer_unq'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='surveyanswer',
            name='survey_answer_unq',
        ),
        migrations.AddConstraint(
            model_name='surveyanswer',
            constraint=models.UniqueConstraint(fields=('enrollment', 'question'), name='survey_answer_unq'),
        ),
    ]
