# Generated by Django 5.2.4 on 2026-09-12 15:08

import datetime
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_surveyanswer_survey_answer_unq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='edu_in_progress',
            field=models.BooleanField(default=True, verbose_name='در حال تحصیل؟'),
        ),
        migrations.AddField(
            model_name='person',
            name='educational_certificate',
            field=models.CharField(choices=[('U', 'زیر دیپلم'), ('D', 'دیپلم'), ('B', 'کارشناسی'), ('G', 'کارشناسی ارشد'), ('C', 'دکتری')], default='U', max_length=1, verbose_name='آخرین مدرک تحصیلی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='is_married',
            field=models.BooleanField(default=False, verbose_name='ازدواج کرده؟'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('P', 'در انتظار نظرسنجی'), ('S', 'ارسال شده'), ('C', 'تایید شده')], default='P', max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2026, 9, 12), verbose_name='تاریخ تولد'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='employmenttype',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_employment_type_title'),
        ),
    ]
