# Generated by Django 5.2.4 on 2026-08-22 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("main", "0004_employmenttype_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("R", "بازنشسته"),
                    ("F", "هیات علمی"),
                    ("E", "کارمند"),
                    ("C", "کارمند شرکتی"),
                ],
                max_length=1,
                verbose_name="نوع استخدام",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="employment_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hired_users",
                to="main.employmenttype",
                verbose_name="نوع استخدام",
            ),
        ),
    ]
