# Generated by Django 5.2.4 on 2026-08-22 04:49

from django.db import migrations


def add_employment_types(apps, schema_editor):
    EmploymentType = apps.get_model("main", "EmploymentType")
    EmploymentType.objects.create(title="کارمند بازنشسته")
    EmploymentType.objects.create(title="کارمند رسمی")
    EmploymentType.objects.create(title="کارمند قراردادی")
    EmploymentType.objects.create(title="کارمند پیمانی")
    EmploymentType.objects.create(title="هیات علمی")
    EmploymentType.objects.create(title="هیات علمی بازنشسته")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_employment_type"),
    ]

    operations = [
        migrations.RunPython(add_employment_types, migrations.RunPython.noop),
    ]
