# Generated by Django 5.2.4 on 2026-09-09 06:28

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_employment_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='employment_end_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='employment_start_date',
        ),
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره حساب'),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, verbose_name='نشانی'),
        ),
        migrations.AddField(
            model_name='user',
            name='available_services',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='خدمات قابل ارائه'),
        ),
        migrations.AddField(
            model_name='user',
            name='bc_issuance_place',
            field=models.CharField(default='همدان', max_length=255, verbose_name='محل صدور شناسنامه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='birth_day',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='روز تولد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='birth_month',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='ماه تولد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='birth_place',
            field=models.CharField(blank=True, max_length=150, verbose_name='محل تولد'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_year',
            field=models.PositiveSmallIntegerField(default=1350, verbose_name='سال تولد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره کارت'),
        ),
        migrations.AddField(
            model_name='user',
            name='changes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد تغییرات'),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='user',
            name='education_certificate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مدرک تحصیلی'),
        ),
        migrations.AddField(
            model_name='user',
            name='extra_text_5',
            field=models.TextField(blank=True, verbose_name='متن اضافه 5'),
        ),
        migrations.AddField(
            model_name='user',
            name='extra_text_6',
            field=models.TextField(blank=True, verbose_name='متن اضافه 6'),
        ),
        migrations.AddField(
            model_name='user',
            name='extra_text_7',
            field=models.TextField(blank=True, verbose_name='متن اضافه 7'),
        ),
        migrations.AddField(
            model_name='user',
            name='extra_text_8',
            field=models.TextField(blank=True, verbose_name='متن اضافه 8'),
        ),
        migrations.AddField(
            model_name='user',
            name='extra_text_9',
            field=models.TextField(blank=True, verbose_name='متن اضافه 9'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], default='M', max_length=1, verbose_name='جنسیت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='iba_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره شبا'),
        ),
        migrations.AddField(
            model_name='user',
            name='insured_computer_code',
            field=models.CharField(blank=True, max_length=54, null=True, verbose_name='کد رایانه بیمه شده'),
        ),
        migrations.AddField(
            model_name='user',
            name='landline_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تلفن ثابت'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization_enter_year',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='سال ورود به سازمان'),
        ),
        migrations.AddField(
            model_name='user',
            name='organizational_unit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='واحد سازمانی'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='09180000000', max_length=20, verbose_name='شماره موبایل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='post_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان پست'),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='زمان آخرین تغییرات'),
        ),
        migrations.AddField(
            model_name='user',
            name='veteran_status',
            field=models.CharField(choices=[('V', 'ایثارگر'), ('D', 'جانباز'), ('S', 'همسر شهید'), ('C', 'فرزند شهید'), ('F', 'آزاده'), ('N', 'ندارد')], default='N', max_length=1, verbose_name='وضعیت ایثارگری'),
            preserve_default=False,
        ),
    ]
