# Generated by Django 5.2.4 on 2026-09-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_employment_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization_enter_year',
            field=models.PositiveSmallIntegerField(default=1360, verbose_name='سال ورود به سازمان'),
            preserve_default=False,
        ),
    ]
