# Generated by Django 5.2.4 on 2026-09-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_organization_enter_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='personnel_code',
        ),
        migrations.AddField(
            model_name='user',
            name='national_code',
            field=models.CharField(default='', max_length=10, unique=True, verbose_name='کد ملی'),
            preserve_default=False,
        ),
    ]
