# Generated by Django 5.2.4 on 2026-09-16 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_user_personnel_code_user_national_code'),
        ('main', '0015_person_edu_in_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bc_issuance_place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='محل صدور شناسنامه'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='روز تولد'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ماه تولد'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_place',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='محل تولد'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سال تولد'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hired_users', to='main.employmenttype', verbose_name='نوع استخدام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'مرد'), ('F', 'زن')], max_length=1, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization_enter_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سال ورود به سازمان'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='veteran_status',
            field=models.CharField(blank=True, choices=[('V', 'ایثارگر'), ('D', 'جانباز'), ('S', 'همسر شهید'), ('C', 'فرزند شهید'), ('F', 'آزاده'), ('N', 'ندارد')], max_length=1, null=True, verbose_name='وضعیت ایثارگری'),
        ),
    ]
