# Generated by Django 5.2.4 on 2026-08-22 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0004_employmenttype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.CharField(max_length=255, unique=True, verbose_name='شناسه نشست پرداخت')),
                ('reference_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='شناسه مرجع پرداخت')),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ پرداختی')),
                ('success', models.BooleanField(default=False, verbose_name='موفقیت آمیز؟')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='main.enrollment', verbose_name='ثبت نام بیمه')),
            ],
        ),
    ]
