# Generated by Django 5.2.4 on 2026-09-01 07:08

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_alter_transaction_created_at_and_more'),
        ('main', '0006_remove_enrollment_contract_enrollment_offer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'تراکنش بانکی', 'verbose_name_plural': 'تراکنش های بانکی'},
        ),
        migrations.CreateModel(
            name='CostRateRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(choices=[('H', 'استخدام شده'), ('F', 'پدر'), ('M', 'مادر'), ('C', 'فرزند'), ('S', 'همسر')], max_length=1, verbose_name='نوع رابطه برای محاسبه قیمت')),
                ('organ_share_percent', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, 'حداقل درصد یارانه، صفر درصد است.'), django.core.validators.MaxValueValidator(100, 'حداکثر درصد یارانه، 100 درصد است.')], verbose_name='درصد سهم سازمان (یارانه)')),
                ('base_premium_cost', models.PositiveBigIntegerField(default=0, verbose_name='هزینه پایه بیمه')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('employment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employmenttype', verbose_name='نوع استخدام')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_rules', to='main.insuranceoffer', verbose_name='قرارداد بیمه سالانه')),
            ],
            options={
                'verbose_name': 'قانون هزینه و یارانه بیمه',
                'verbose_name_plural': 'قوانین هزینه و یارانه بیمه',
            },
        ),
        migrations.CreateModel(
            name='ExceptionalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('condition', models.JSONField(help_text='این فیلد از استاندارد JsonLogic استفاده می کند.')),
                ('priority', models.PositiveSmallIntegerField(default=0, verbose_name='اولویت')),
                ('new_organ_share', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'حداقل درصد یارانه، صفر درصد است.'), django.core.validators.MaxValueValidator(100, 'حداکثر درصد یارانه، 100 درصد است.')], verbose_name='درصد سهم سازمان (یارانه)')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال؟')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ساخت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('rate_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='financial.costraterule', verbose_name='قانون')),
            ],
            options={
                'verbose_name': 'شرط استثنایی',
                'verbose_name_plural': 'شروط استثنایی',
            },
        ),
    ]
