# Generated by Django 5.2.4 on 2026-09-01 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_alter_transaction_options_costraterule_and_more'),
        ('main', '0007_rename_end_date_insurancecontract_coverage_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costraterule',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_rules', to='main.insuranceoffer', verbose_name='پیشنهاد بیمه سالانه'),
        ),
    ]
