# Generated by Django 5.2.4 on 2026-09-12 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_alter_costraterule_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
